
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: docker compose
    before: |
      git config --global alias.tree 'log --graph --all --format="%x09%C(cyan bold)%an%Creset%x09%C(yellow)%h%Creset %C(magenta reverse)%d%Creset %s"'
      git config --global alias.tree-date 'log --graph --all --date-order --format="%x09%C(cyan bold)%an%Creset%x09%C(yellow)%h%Creset %C(magenta reverse)%d%Creset %s"'
    init: |
      docker compose build
    command: |
      docker compose up -d
      ./cmd composer install
vscode:
  extensions:
    - devsense.phptools-vscode
    - devsense.composer-php-vscode
    - devsense.intelli-php-vscode
    - devsense.profiler-php-vscode
    - getpsalm.psalm-vscode-plugin
    - junstyle.php-cs-fixer
