
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: docker compose
    init: |
      docker compose --profile extra build --no-cache
#    command: |
#      docker compose up
vscode:
  extensions:
    - devsense.phptools-vscode
    - getpsalm.psalm-vscode-plugin
