version: '3.8'

services:
  php-cli:
    container_name: php-cli
    build: ./docker/php
    volumes:
      - type: bind
        source: ./app
        target: /app
    working_dir: /app
    tty: true
    stdin_open: true